[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Greentree Radio"
authors = [{name = "JayGreentree", email = "jgreentreevin@gmail.com"}]
dynamic = ["version", "description"]
